<?php
// TOP
define('_titleweb','Sunrise Kidz');
define('_teacher','Teacher');
define('_children','Children');
define('_lesson','Lessons');
define('_class','Classes');
define('_syslog','System Log');
define('_newsletter','Newsletter');

# giao vien
define('_school','Campus');
define('_principle','Principal');
define('_headteacher','Head teacher');
define('_ht','HT');
define('_level','Level');
define('_reportto','Report to');
define('_teacherid','Teacher ID');
define('_fname','Family name');
define('_mname','First name');
define('_lname','Nickname');
define('_gender','Gender');
define('_nationality','Nationality');
define('_onumber','Office number');
define('_mnumber','Mobile number');
define('_emailaddress','Email Address');
define('_fbaccount','Facebook account');
define('_classgr','Class group');
define('_namvaotruong','Year in Sunrise Kidz');
define('_nonamvaotruong','You not enter year in Sunrise Kidz. Please enter !!!');
define('_invalidnamvaotruong','Year in Sunrise Kidz is digit and length 4 digits. Please re-enter !!!');
define('_schoolbrand','Campus');
define('_addschool','Add new campus');
define('_editschool','Edit name of campus');
define('_tenchinhanh','Name of campus');
define('_nobrandvn','You not enter name of campus. Please enter !!!');
define('_nobranden','You not enter school brand English. Please enter !!!');
define('_brandexist','Name of brand existed on system.');
define('_addschoolsucc','Add new campus successfully !');
define('_editschoolsucc','Edit campus successfully !');
define('_condelsc','Are you sure want to delete this campus ?');
define('_stillteacher','This campus is still the teacher should not be deleted.<br />To delete a teacher you have to switch to another campus before !!!');
define('_xoatc','Deleted this campus successfully !');

define('_image','Image');
define('_chooseimg','Choose image');
define('_add','Add');
define('_edit','Edit');
define('_addnew','Add new');
define('_noteacher','Temporary no teacher in this campus !!!');

// add new teacher
define('_addnewteacher','Add new teacher');
define('_choseteacher','Choose teacher');
define('_chooseschool','Choose campus');
define('_nocs','You not choose campus.');
define('_male','Male');
define('_female','Female');
define('_cfemail','Confirm email');
define('_password','Password');
define('_cfpassword','Confirm password');
define('_notcid','You not enter teacher ID. Please enter !!!');
define('_nofname','You not enter first name. Please enter !!!');
define('_nomname','You not enter middle name. Please enter !!!');
define('_nolname','You not enter family name. Please enter !!!');
define('_nonationality','You not enter nationality. Please enter !!!');
define('_noonumber','You not enter office number. Please enter !!!');
define('_nomnumber','You not enter mobile number. Please enter !!!');
define('_noemail','You not enter email address. Please enter !!!');
define('_emailinvalid','Email address is invalid.');
define('_nocfemail','You not enter confirm email. Please enter !!!');
define('_emailnotmatch','Email address is not match');
define('_nopass','You not enter password. Please enter !!!');
define('_nocfpass','You not enter confirm password. Please enter !!!');
define('_passnotmatch','Password is not match.');
define('_noclassgr','You not enter class group. Please enter !!!');
define('_norep','You not choose teacher to report to. Please choose !!!');
define('_noimage','You not choose image. Please choose !!!');
define('_addtcsucc','Add teacher successfully !!!');
define('_tcidexist','Teacher ID exist on system. Please enter another teacher id !!!');
define('_emailexist','Email exist on system. Please enter another email !!!');
define('_condelteacher','Are you sure want to delete this teacher ?');

define('_xoattc','Deleted successfully !');
define('_stillhead','Cannot delete this account. Please transfer all the Teachers to other Head Teachers.');
define('_stillcl','Cannot delete this account. Please clear the work schedule of this Teacher.');
// change image
define('_changeimage','Change avatar');
define('_changimgsucc','Change avatar successfully !');
define('_update','Update');

// change level
define('_changelevel','Change level');
define('_changelvsucc','Change level successfully !');

define('_editteacher','Edit teacher');
define('_changepass','Change password');
define('_oldpassword','Old password');
define('_newpassword','New password');
define('_nooldpass','You not enter old password. Please enter !!!');
define('_nonewpass','You not enter new password. Please enter !!!');
define('_oldpwrong','You enter old password is incorrect. Please reenter !!!');
define('_changepsucc','Change password successfully !');
define('_renewpassword','Confirm new password');
define('_norenewpassword','You not enter confirm new password. Please enter !!!');
define('_passwordnomatch','Password not match !!!');

// children
define('_name','Name');
define('_father','Father');
define('_mother','Mother');
define('_addnewchild','Add new child');
define('_childrenid','Children ID');
define('_dob','D.o.B');
define('_currentage','Current age');
define('_month','Month');
define('_yearold','Years old');
define('_chooseage','Choose age');
define('_choosecg','Choose class ground');
define('_mothers',"Mother's");
define('_fathers',"Father's");
define('_tinhcach','Characteristics');
define('_cpofmothers',"Change mother's password");
define('_cpoffathers',"Change father's password");
define('_contactnm','contact number');
define('_address','address');
define('_ifdif','(If different)');
define('_thang1','January');
define('_thang2','February');
define('_thang3','March');
define('_thang4','April');
define('_thang5','May');
define('_thang6','June');
define('_thang7','July');
define('_thang8','August');
define('_thang9','September');
define('_thang10','October');
define('_thang11','November');
define('_thang12','December');
define('_t2','Mo');
define('_t3','Tu');
define('_t4','We');
define('_t5','Th');
define('_t6','Fr');
define('_t7','Sa');
define('_chunhat','Su');
define('_thu2','Monday');
define('_thu3','Tuesday');
define('_thu4','Wednesday');
define('_thu5','Thursday');
define('_thu6','Friday');
define('_thu7','Saturday');
define('_cnhat','Sunday');
// add children
define('_nocid','You not enter children ID. Please enter !!!');
define('_nodob','You not enter D.o.B. Please enter !!!');
define('_noage','You not chooose age group. Please choose !!!');
define('_nocg','You not choose class group. Please choose !!!');
define('_nofathername',"You not enter father's name. Please enter !!!");
define('_nofathernumber',"You not enter father's contact number. Please enter !!!");
define('_nofatheraddress',"You not enter father's address. Please enter !!!");
define('_nomothername',"You not enter mother's name. Please enter !!!");
define('_nomothernumber',"You not enter mother's contact number. Please enter !!!");
define('_existcid','Children ID existed on system. Please reenter another children ID !!!');
define('_addcrsucc','Add child successfully !');
define('_changechild',"Change child's information");
define('_changefather',"Change father's information");
define('_changemother',"Change mother's information");
define('_updateinfosucc',"Update information successfully");
define('_condelchild','Are you sure want to delete this child ?');

define('_accname','Account Name');
define('_actdetail','Action Detail');
define('_from','From');
define('_to','To');
define('_addnta','Add new teacher account');
define('_addffc','Add feedback for child');
define('_edittl','Edit teacher level');
define('_download','Download');
define('_search','Search');
define('_nofound','No record found !!!');

// lessons
define('_addnewclass','Add new class');
define('_editclass','Edit class name');
define('_tenlop','Class name');
define('_notenlop','You not enter class name. Please enter !');
define('_existtenlop','Class name has existed. Please enter another class name !');
define('_addtenlopsucc','Add class successfully !');
define('_edittenlopsucc','Edit class name successfully !');
define('_condelclass','Are you sure want to delete this class name ?');
define('_agegroup','Age group');
define('_lesspractice','Subject');
define('_lessdetail','Detail of lesson');
define('_desdetail','Description lesson');
define('_lessday','Day');
define('_lessweek','Week');
define('_addpractise','Add practise');
define('_editpractise','Edit practise');
define('_lessname','Title');
define('_noprtv','You not enter title Vietnamese. Please enter !!!');
define('_noprte','You not enter title English. Please enter !!!');
define('_lessprex','This practise existed !!!');
define('_addprsucc','Add practise successfully !');
define('_editprsucc','Edit practise successfully !');
define('_condelpr','<strong>Note:</strong> When deleting this practice every lesson and memorize all the details of it will be deleted.<br />Are you sure want to delete it ???');
define('_ok','OK');
define('_cancel','Cancel');

define('_addlesson','Add lesson');
define('_editlesson','Edit lesson');
define('_chooseprac','Choose practise');
define('_lesslex','This lesson existed !!!');
define('_addlesssucc','Add lesson successfully !');
define('_editlesssucc','Edit lesson successfully !');
define('_condelless','<strong>Note: </strong> When deleting this lesson every detail of it will be deleted.<br />Are you sure want to delete it ???');

define('_adddetail','Add new content of lesson');
define('_editdetail','Update content of lesson');
define('_nocontdetailvn','You not enter content of lesson Vietnamese. Please enter !!!');
define('_nocontdetailen','You not enter content of lesson English. Please enter !!!');
define('_ngaythang','Date');
define('_nongaythang','You not choose date. Please choose !!!');
define('_addcontsucc','Add content of lesson successfully !');
define('_editcontsucc','Update content of lesson successfully !');
define('_contdel','Are you sure want to delete this content ?');

// classes
define('_mark','Proficiency');
define('_comment','Comment');
define('_cuoithang','End of ');
define('_averagemark','Average mark');
define('_blc','General comment');
define('_chuachontruong','You not choose campus. Please choose !');
define('_chuachonlop','You not choose class group. Please choose !');
define('_chuachonhs','You not choose child. Please choose !');
define('_chuachongi','You not choose campus, class group, child. Please choose !');
define('_chuabldutuan','To comment for child at the end of month, you need assessment at least 4 weeks for this subject !!!');

// login
define('_login','Login');
define('_username','Username');
define('_password','Password');
define('_nousername','You not enter username. Please enter !');
define('_nopassword','You not enter password. Please enter !');
define('_noexistuser','Username not exists in the system. Please enter again !');
define('_invalidpass','Password is incorrect. Please enter again !');
define('_notexistu','Username not exist in the system.');
define('_notrightpass','Password is incorrect.');
define('_loginsucc','Login successfully !');
define('_welcome','Welcome');
define('_logout','Logout');

// mail
define('_hi','Dear');
define('_titlemailcp','Confirm change password');
define('_wehaverequest','We have received a request to change your Sunrise Kidz account password. Please see the following as your new password:');
define('_ifdidnot','If you did not send this request, please contact our administration for immediately support.');
define('_regards','Regards,');

// explain for proficiency
define('_onestar','Exploring new material');
define('_twostar','Building competency to fluency');
define('_threestar','Seamlessly work with material and able to slow other');

define('_title','Title');
define('_addnewsletter','Add newsletter');
define('_editnewsletter','Update newsletter');
define('_attachfile','Attachment file');
define('_content','Content');
define('_notitlevn','You not enter title in Vietnamese');
define('_notitleen','You not enter title in English.');
define('_themthongbaotc','Add newsletter successfully !');
define('_suathongbaotc','Update newsletter successfully !');
define('_condelnewsletter','Are you sure want to delete this newsletter ?');
define('_nocontent','You not enter content');
define('_back','Back');
define('_file','File');
define('_choosefile','Choose file');
define('_nochoosefile','You not choose file.');
define('_attachfiletc','Add attachment file successfully.');

define('_comcorner','Communication corner');
define('_noidung','Content');
define('_xemdaydu','View all of this comment.');
define('_themcom','Add new comment');
define('_themcomtc','Add comment successfully');
define('_tungay','Week from date');
define('_denngay','Week to date');
define('_notungay','You not input week from date');
define('_nodenngay','You not input week to date');
define('_nhanxet','Comment');
define('_phanhoi','Reply');
define('_nonhanxet','You not input comment');
define('_viewreply','View reply of this comment');
define('_suanhanxet','Edit this comment');
define('_xoanhanxet','Delete this comment');
define('_ccxoanhanxet','Are you sure want to delete this comment ?');
define('_chuacophanhoi','No reply.');
define('_nhanxet250tu','Comment content is not exceeding 250 words');
define('_suanhanxet','Edit comment');
define('_suacomtc','Edit comment successfully');
define('_delconcom','Are you sure want to delete this comment and reply ?');
define('_xoathanhcong','Delete successfully');
define('_themngay1sao','Add date 1 star');
define('_themngay2sao','Add date 2 star');
define('_themngay3sao','Add date 3 star');
define('_suangay1sao','Edit date 1 star');
define('_suangay2sao','Edit date 2 star');
define('_suangay3sao','Edit date 3 star');
define('_chuachonngay','You not choose date');
define('_themngaytc','Add date successfully');
define('_suangaythanhcong','Edit date successfully');
define('_ngaythang','Date');
define('_filethongbao','File Newsletter');
define('_chuaco','Not yet');
define('_quanlyuser','Manage User');
define('_tenorcv','Name / Position');
define('_tendangnhap','Username');
define('_quyen','Permission');
define('_dnlancuoi','Last login');
define('_kichhoat','Active');
define('_suathongtin','Edit');
define('_suathongtinuser',"Change user's information");
define('_themuser','Add User');
define('_doimatkhau','Change password');
define('_thaydoi','Change');
define('_notenorcv','You not enter name / position. Please enter !');
define('_themusersucc','Add user successfully');
define('_capnhatusersucc','Edit user successfully');
?>